
export const REQUEST_PRODUCTS = "REQUEST_PRODUCTS";
export const SUCCESS_PRODUCTS = "SUCCESS_PRODUCTS";
export const FAILURE_PRODUCTS = "FAILURE_PRODUCTS";

export const REQUEST_VIEWCART = "REQUEST_VIEWCART";
export const SUCCESS_VIEWCART = "SUCCESS_VIEWCART";
export const FAILURE_VIEWCART = "FAILURE_VIEWCART";


